// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MACHINEBISS_Web.Models.EFatura.EFatGelen;
//
//    var gelenFaturaResponse = GelenFaturaResponse.FromJson(jsonString);

namespace MACHINEBISS_Web.Models.EFatura.EFatGelen
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GelenFaturaResponse
    {
        [JsonProperty("STATE", NullValueHandling = NullValueHandling.Ignore)]
        public virtual bool? State { get; set; }

        [JsonProperty("PARAMS", NullValueHandling = NullValueHandling.Ignore)]
        public virtual GelenFaturaResponseParams Params { get; set; }
    }

    public partial class GelenFaturaResponseParams
    {
        [JsonProperty("Params", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Params Params { get; set; }
    }

    public partial class ValClsReturnParams
    {
        [JsonProperty("Result", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Params Result { get; set; }
    }

    public partial class ValClsReturn
    {
        [JsonProperty("STATE", NullValueHandling = NullValueHandling.Ignore)]
        public virtual bool? State { get; set; }

        [JsonProperty("PARAMS", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ValClsReturnParams Params { get; set; }
    }

    public partial class Param
    {
        [JsonProperty("VAL_CLS_RETURN", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ValClsReturn ValClsReturn { get; set; }

        [JsonProperty("TypeName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string TypeName { get; set; }
    }

    public partial class ValLCls25
    {
        [JsonProperty("FIELD_NAME", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string FieldName { get; set; }

        [JsonProperty("STATE", NullValueHandling = NullValueHandling.Ignore)]
        public virtual bool? State { get; set; }

        [JsonProperty("PARAM", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Param Param { get; set; }
    }

    public partial class Params
    {
        [JsonProperty("ORDER", NullValueHandling = NullValueHandling.Ignore)]
        public virtual long? Order { get; set; }

        [JsonProperty("CODE", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Code { get; set; }

        [JsonProperty("VAL_L_CLS25", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<ValLCls25> ValLCls25 { get; set; }

        [JsonProperty("TypeName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string TypeName { get; set; }

        [JsonProperty("VAL_JOBJECT", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ValJobject ValJobject { get; set; }
    }

    public partial class ValJobject
    {
        [JsonProperty("s:Envelope", NullValueHandling = NullValueHandling.Ignore)]
        public virtual SEnvelope SEnvelope { get; set; }
    }

    public partial class SEnvelope
    {
        [JsonProperty("@xmlns:s", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsS { get; set; }

        [JsonProperty("s:Body", NullValueHandling = NullValueHandling.Ignore)]
        public virtual SBody SBody { get; set; }
    }

    public partial class SBody
    {
        [JsonProperty("GetInvoicesResponse", NullValueHandling = NullValueHandling.Ignore)]
        public virtual GetInvoicesResponse GetInvoicesResponse { get; set; }
    }

    public partial class GetInvoicesResponse
    {
        [JsonProperty("@xmlns", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri Xmlns { get; set; }

        [JsonProperty("GetInvoicesResult", NullValueHandling = NullValueHandling.Ignore)]
        public virtual GetInvoicesResult GetInvoicesResult { get; set; }
    }

    public partial class GetInvoicesResult
    {
        [JsonProperty("@xmlns:a", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsA { get; set; }

        [JsonProperty("@xmlns:i", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsI { get; set; }

        [JsonProperty("Header", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Header Header { get; set; }

        [JsonProperty("a:Invoices", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AInvoices AInvoices { get; set; }

        [JsonProperty("a:RemainedInvoiceCount", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? ARemainedInvoiceCount { get; set; }
    }

    public partial class AInvoices
    {
        [JsonProperty("a:IncomingInvoice", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<AIncomingInvoice> AIncomingInvoice { get; set; }
    }

    public partial class AIncomingInvoice
    {
        [JsonProperty("a:Body", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ABody ABody { get; set; }

        [JsonProperty("a:Header", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AHeader AHeader { get; set; }

        [JsonProperty("a:ViewContent", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent AViewContent { get; set; }
    }

    public partial class ABody
    {
        [JsonProperty("@xmlns:b", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsB { get; set; }

        [JsonProperty("b:AccountingCost", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BAccountingCost { get; set; }

        [JsonProperty("b:AccountingCustomerParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAccountingCustomerParty BAccountingCustomerParty { get; set; }

        [JsonProperty("b:AccountingSupplierParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAccountingSupplierParty BAccountingSupplierParty { get; set; }

        [JsonProperty("b:AdditionalDocumentReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAdditionalDocumentReference BAdditionalDocumentReference { get; set; }

        [JsonProperty("b:AllowanceCharge", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ABodyBAllowanceCharge BAllowanceCharge { get; set; }

        [JsonProperty("b:AllowanceCharges")]
        public virtual ABodyBAllowanceCharges BAllowanceCharges { get; set; }

        [JsonProperty("b:BillingReference")]
        public virtual dynamic BBillingReference { get; set; }

        [JsonProperty("b:BuyerCustomerParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BBuyerCustomerParty { get; set; }

        [JsonProperty("b:ContractDocumentReference")]
        public virtual dynamic BContractDocumentReference { get; set; }

        [JsonProperty("b:CopyIndicator", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? BCopyIndicator { get; set; }

        [JsonProperty("b:Delivery")]
        public virtual dynamic BDelivery { get; set; }

        //[JsonProperty("b:DespatchDocumentReference")]
        //public virtual BDespatchDocumentReference BDespatchDocumentReference { get; set; }

        [JsonProperty("b:DocumentCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BDocumentCurrencyCode { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:InvoiceLine", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ABodyBInvoiceLine BInvoiceLine { get; set; }

        [JsonProperty("b:InvoicePeriod", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BInvoicePeriod { get; set; }

        [JsonProperty("b:InvoiceTypeCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BInvoiceTypeCode { get; set; }

        [JsonProperty("b:IssueDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BIssueDateTime { get; set; }

        [JsonProperty("b:LegalMonetaryTotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BLegalMonetaryTotal BLegalMonetaryTotal { get; set; }

        //[JsonProperty("b:Notes", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual ABodyBNotes BNotes { get; set; }

        [JsonProperty("b:OrderReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BOrderReference BOrderReference { get; set; }

        [JsonProperty("b:OriginatorDocumentReference")]
        public virtual dynamic BOriginatorDocumentReference { get; set; }

        [JsonProperty("b:PaymentAlternativeCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPaymentAlternativeCurrencyCode { get; set; }

        [JsonProperty("b:PaymentAlternativeExchangeRate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPaymentAlternativeExchangeRate { get; set; }

        [JsonProperty("b:PaymentCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPaymentCurrencyCode { get; set; }

        [JsonProperty("b:PaymentExchangeRate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPaymentExchangeRate { get; set; }

        [JsonProperty("b:PaymentMeans")]
        public virtual ABodyBPaymentMeans BPaymentMeans { get; set; }

        [JsonProperty("b:PaymentTerms", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPaymentTerms BPaymentTerms { get; set; }

        [JsonProperty("b:PricingCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPricingCurrencyCode { get; set; }

        [JsonProperty("b:PricingExchangeRate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPricingExchangeRate { get; set; }

        [JsonProperty("b:ProfileID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BProfileId { get; set; }

        [JsonProperty("b:ReceiptDocumentReference")]
        public virtual dynamic BReceiptDocumentReference { get; set; }

        [JsonProperty("b:SellerSupplierParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BSellerSupplierParty { get; set; }

        [JsonProperty("b:TaxCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTaxCurrencyCode { get; set; }

        [JsonProperty("b:TaxExchangeRate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BTaxExchangeRate { get; set; }

        [JsonProperty("b:TaxRepresentativeParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BTaxRepresentativeParty { get; set; }

        [JsonProperty("b:TaxTotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ABodyBTaxTotal BTaxTotal { get; set; }

        [JsonProperty("b:UUID", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Guid? BUuid { get; set; }

        [JsonProperty("b:WithholdingTaxTotal")]
        public virtual dynamic BWithholdingTaxTotal { get; set; }
    }

    public partial class AViewContent
    {
        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class BAccountingCustomerParty
    {
        [JsonProperty("b:DespatchContact", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BDespatchContact { get; set; }

        [JsonProperty("b:Party", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAccountingCustomerPartyBParty BParty { get; set; }
    }

    public partial class BAccountingCustomerPartyBParty
    {
        [JsonProperty("b:AgentParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAgentParty BAgentParty { get; set; }

        [JsonProperty("b:Contact", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BContact BContact { get; set; }

        [JsonProperty("b:EndpointID", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BEndpointId { get; set; }

        [JsonProperty("b:IndustryClassificationCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BIndustryClassificationCode { get; set; }

        //[JsonProperty("b:PartyIdentifications", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual BPartyBPartyIdentifications BPartyIdentifications { get; set; }

        [JsonProperty("b:PartyLegalEntity")]
        public virtual dynamic BPartyLegalEntity { get; set; }

        [JsonProperty("b:PartyName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BPartyName { get; set; }

        [JsonProperty("b:PartyTax", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPartyTax { get; set; }

        [JsonProperty("b:Person", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPerson BPerson { get; set; }

        [JsonProperty("b:PhysicalLocation", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPhysicalLocation { get; set; }

        [JsonProperty("b:PostalAddress", NullValueHandling = NullValueHandling.Ignore)]
        public virtual PurpleBPostalAddress BPostalAddress { get; set; }

        [JsonProperty("b:WebsiteURI", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BWebsiteUri { get; set; }
    }

    public partial class BAgentParty
    {
        [JsonProperty("b:Contact", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BContact BContact { get; set; }

        [JsonProperty("b:IndustryClassificationCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BIndustryClassificationCode { get; set; }

        //[JsonProperty("b:PartyIdentifications", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual BPartyBPartyIdentifications BPartyIdentifications { get; set; }

        [JsonProperty("b:PartyName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPartyName { get; set; }

        [JsonProperty("b:PartyTax", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPartyTax { get; set; }

        [JsonProperty("b:Person", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPerson { get; set; }

        [JsonProperty("b:PostalAddress", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAgentPartyBPostalAddress BPostalAddress { get; set; }

        [JsonProperty("b:WebsiteURI", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BWebsiteUri { get; set; }

        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class BContact
    {
        [JsonProperty("b:ElectronicMail", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BElectronicMail { get; set; }

        [JsonProperty("b:Name", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BName { get; set; }

        [JsonProperty("b:Note", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BNote { get; set; }

        [JsonProperty("b:OtherCommunication", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BOtherCommunication { get; set; }

        [JsonProperty("b:Telefax", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTelefax { get; set; }

        [JsonProperty("b:Telephone", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTelephone { get; set; }

        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class BAgentPartyBPartyIdentifications
    {
        [JsonProperty("b:PartyIdentification", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPartyIdentification BPartyIdentification { get; set; }
    }

    public partial class BPartyIdentification
    {
        [JsonProperty("b:SchemeID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BSchemeId { get; set; }

        [JsonProperty("b:Value", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BValue { get; set; }
    }

    public partial class BAgentPartyBPostalAddress
    {
        [JsonProperty("b:BlockName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBlockName { get; set; }

        [JsonProperty("b:BuildingName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingName { get; set; }

        [JsonProperty("b:BuildingNumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingNumber { get; set; }

        [JsonConverter(typeof(NilStringParseCodeConverter))]
        [JsonProperty("b:CityName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BCityName { get; set; }

        [JsonProperty("b:CitySubdivisionName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCitySubdivisionName { get; set; }

        [JsonProperty("b:Country", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BCountry BCountry { get; set; }

        [JsonProperty("b:District", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDistrict { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:PostBox", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPostBox { get; set; }

        [JsonProperty("b:PostalZone", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilLongParseCodeConverter))]
        public virtual long? BPostalZone { get; set; }

        [JsonProperty("b:Region", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRegion { get; set; }

        [JsonProperty("b:Room", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRoom { get; set; }

        [JsonProperty("b:StreetName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BStreetName { get; set; }
    }

    public partial class BCountry
    {
        [JsonProperty("b:IdentificationCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BIdentificationCode { get; set; }

        [JsonProperty("b:Name", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BName { get; set; }
    }

    public partial class BPartyBPartyIdentifications
    {
        [JsonProperty("b:PartyIdentification", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<Identification> BPartyIdentification { get; set; }
    }

    public partial class Identification
    {
        [JsonProperty("b:SchemeID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BSchemeId { get; set; }

        [JsonProperty("b:Value", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BValue { get; set; }
    }

    public partial class BPerson
    {
        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }

        [JsonProperty("b:FamilyName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BFamilyName { get; set; }

        [JsonProperty("b:FinancialAccount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BFinancialAccount { get; set; }

        [JsonProperty("b:FirstName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BFirstName { get; set; }

        [JsonProperty("b:IdentityDocumentReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BIdentityDocumentReference { get; set; }

        [JsonProperty("b:MiddleName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BMiddleName { get; set; }

        [JsonProperty("b:NameSuffix", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BNameSuffix { get; set; }

        [JsonProperty("b:NationalityID", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BNationalityId { get; set; }

        [JsonProperty("b:Title", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BTitle { get; set; }
    }

    public partial class PurpleBPostalAddress
    {
        [JsonProperty("b:BlockName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBlockName { get; set; }

        [JsonProperty("b:BuildingName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingName { get; set; }

        [JsonProperty("b:BuildingNumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingNumber { get; set; }

        [JsonProperty("b:CityName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCityName { get; set; }

        [JsonProperty("b:CitySubdivisionName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCitySubdivisionName { get; set; }

        [JsonProperty("b:Country", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BCountry BCountry { get; set; }

        [JsonProperty("b:District", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDistrict { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:PostBox", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPostBox { get; set; }

        [JsonProperty("b:PostalZone", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilLongParseCodeConverter))]
        public virtual long? BPostalZone { get; set; }

        [JsonProperty("b:Region", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRegion { get; set; }

        [JsonProperty("b:Room", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRoom { get; set; }

        [JsonProperty("b:StreetName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BStreetName { get; set; }
    }

    public partial class BAccountingSupplierParty
    {
        [JsonProperty("b:DespatchContact", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDespatchContact { get; set; }

        [JsonProperty("b:Party", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAccountingSupplierPartyBParty BParty { get; set; }
    }

    public partial class BAccountingSupplierPartyBParty
    {
        [JsonProperty("b:AgentParty", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BAgentParty { get; set; }

        [JsonProperty("b:Contact", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BContact BContact { get; set; }

        [JsonProperty("b:EndpointID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BEndpointId { get; set; }

        [JsonProperty("b:IndustryClassificationCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BIndustryClassificationCode { get; set; }

        [JsonProperty("b:PartyIdentifications", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPartyBPartyIdentifications BPartyIdentifications { get; set; }

        [JsonProperty("b:PartyLegalEntity")]
        public virtual dynamic BPartyLegalEntity { get; set; }

        [JsonProperty("b:PartyName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPartyName { get; set; }

        [JsonProperty("b:PartyTax", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPartyTax { get; set; }

        [JsonProperty("b:Person", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPerson BPerson { get; set; }

        [JsonProperty("b:PhysicalLocation", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPhysicalLocation { get; set; }

        [JsonProperty("b:PostalAddress", NullValueHandling = NullValueHandling.Ignore)]
        public virtual FluffyBPostalAddress BPostalAddress { get; set; }

        [JsonProperty("b:WebsiteURI", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BWebsiteUri { get; set; }
    }

    public partial class FluffyBPostalAddress
    {
        [JsonProperty("b:BlockName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBlockName { get; set; }

        [JsonProperty("b:BuildingName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingName { get; set; }

        [JsonProperty("b:BuildingNumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuildingNumber { get; set; }

        [JsonProperty("b:CityName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCityName { get; set; }

        [JsonProperty("b:CitySubdivisionName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCitySubdivisionName { get; set; }

        [JsonProperty("b:Country", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BCountry BCountry { get; set; }

        [JsonProperty("b:District", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDistrict { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:PostBox", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BPostBox { get; set; }

        [JsonProperty("b:PostalZone", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilLongParseCodeConverter))]
        public virtual long? BPostalZone { get; set; }

        [JsonProperty("b:Region", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRegion { get; set; }

        [JsonProperty("b:Room", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BRoom { get; set; }

        [JsonProperty("b:StreetName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BStreetName { get; set; }
    }

    public partial class BAdditionalDocumentReference
    {
        [JsonProperty("b:DocumentReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BDocumentReferenceUnion? BDocumentReference { get; set; }
    }

    public partial class BDocumentReferenceElement
    {
        [JsonProperty("b:Attachment", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAttachment BAttachment { get; set; }

        [JsonProperty("b:DocumentDescription", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BDocumentDescription BDocumentDescription { get; set; }

        [JsonProperty("b:DocumentType", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDocumentType { get; set; }

        [JsonProperty("b:DocumentTypeCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDocumentTypeCode { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:IssueDate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BIssueDate { get; set; }

        [JsonProperty("b:IssuerParty", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BIssuerParty { get; set; }

        [JsonProperty("b:ValidityPeriod", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BValidityPeriod { get; set; }
    }

    public partial class BAttachment
    {
        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }

        [JsonProperty("b:EmbeddedDocumentBinaryObject", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BEmbeddedDocumentBinaryObject { get; set; }

        [JsonProperty("b:ExternalReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BExternalReference { get; set; }

        [JsonProperty("b:FileName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BFileName { get; set; }

        [JsonProperty("b:MimeCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BMimeCode { get; set; }
    }

    public partial class BDocumentDescription
    {
        [JsonProperty("@xmlns:c", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsC { get; set; }
    }

    public partial class ABodyBAllowanceCharge
    {
        [JsonProperty("b:AllowanceChargeReason", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BAllowanceChargeReason { get; set; }


        [JsonProperty("b:Amount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAmount BAmount { get; set; }

        [JsonProperty("b:BaseAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Amount BBaseAmount { get; set; }

        [JsonProperty("b:ChargeIndicator", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? BChargeIndicator { get; set; }

        [JsonProperty("b:MultiplierFactorNumeric", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BMultiplierFactorNumeric { get; set; }

        [JsonProperty("b:PerUnitAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPerUnitAmount { get; set; }

        [JsonProperty("b:SequenceNumeric", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BSequenceNumeric { get; set; }

        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class BAmount
    {
        [JsonProperty("b:CurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BCurrencyCode { get; set; }

        [JsonConverter(typeof(DoubleParseStringConverter))]
        [JsonProperty("b:Value", NullValueHandling = NullValueHandling.Ignore)]
        public virtual double? BValue { get; set; }
    }

    public partial class Amount
    {
        [JsonProperty("b:CurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BCurrencyCode { get; set; }

        [JsonConverter(typeof(DoubleParseStringConverter))]
        [JsonProperty("b:Value", NullValueHandling = NullValueHandling.Ignore)]
        public virtual double BValue { get; set; }

        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class ABodyBAllowanceCharges
    {
        [JsonProperty("b:AllowanceCharge", NullValueHandling = NullValueHandling.Ignore)]
        public virtual ABodyBAllowanceCharge BAllowanceCharge { get; set; }
    }

    public partial class BDespatchDocumentReference
    {
        [JsonProperty("b:DocumentReference", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BDespatchDocumentReferenceBDocumentReference BDocumentReference { get; set; }
    }

    public partial class BDespatchDocumentReferenceBDocumentReference
    {
        [JsonProperty("b:Attachment", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BAttachment { get; set; }

        [JsonProperty("b:DocumentDescription", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BDocumentDescription BDocumentDescription { get; set; }

        [JsonProperty("b:DocumentType", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BDocumentType { get; set; }

        [JsonProperty("b:DocumentTypeCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BDocumentTypeCode { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:IssueDate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BIssueDate { get; set; }

        [JsonProperty("b:IssuerParty", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BIssuerParty { get; set; }

        [JsonProperty("b:ValidityPeriod", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BValidityPeriod { get; set; }
    }

    public partial class ABodyBInvoiceLine
    {
        [JsonProperty("b:InvoiceLine", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<BInvoiceLineElement> BInvoiceLine { get; set; }
    }

    public partial class BInvoiceLineElement
    {
        [JsonProperty("b:AllowanceCharge", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAllowanceChargeElement BAllowanceCharge { get; set; }

        [JsonProperty("b:AllowanceCharges", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BInvoiceLineBAllowanceCharges BAllowanceCharges { get; set; }

        [JsonProperty("b:Delivery")]
        public virtual dynamic BDelivery { get; set; }

        [JsonProperty("b:DespatchLineReference")]
        public virtual dynamic BDespatchLineReference { get; set; }

        [JsonProperty("b:InvoicedQuantityUnitCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BInvoicedQuantityUnitCode { get; set; }

        [JsonConverter(typeof(DoubleParseStringConverter))]
        [JsonProperty("b:InvoicedQuantityValue", NullValueHandling = NullValueHandling.Ignore)]
        public virtual double BInvoicedQuantityValue { get; set; }

        [JsonProperty("b:Item", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BItem BItem { get; set; }

        [JsonProperty("b:LineExtensionAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BLineExtensionAmount { get; set; }

        //[JsonProperty("b:Note")]
        //public virtual BNote? BNote { get; set; }

        //[JsonProperty("b:Notes", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual BInvoiceLineBNotes BNotes { get; set; }

        [JsonProperty("b:OrderLineReference")]
        public virtual dynamic BOrderLineReference { get; set; }

        [JsonProperty("b:Price", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BPrice { get; set; }

        [JsonProperty("b:ReceiptLineReference")]
        public virtual dynamic BReceiptLineReference { get; set; }

        [JsonProperty("b:SubInvoiceLine")]
        public virtual dynamic BSubInvoiceLine { get; set; }

        [JsonProperty("b:TaxTotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BInvoiceLineBTaxTotal BTaxTotal { get; set; }

        [JsonProperty("b:WithholdingTaxTotal")]
        public virtual dynamic BWithholdingTaxTotal { get; set; }
    }

    public partial class BAllowanceChargeElement
    {
        [JsonProperty("b:AllowanceChargeReason", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BAllowanceChargeReason { get; set; }

        [JsonProperty("b:Amount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BAmount { get; set; }

        [JsonProperty("b:BaseAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BBaseAmount { get; set; }

        [JsonProperty("b:ChargeIndicator", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? BChargeIndicator { get; set; }

        [JsonProperty("b:MultiplierFactorNumeric", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BMultiplierFactorNumeric { get; set; }

        [JsonProperty("b:PerUnitAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPerUnitAmount { get; set; }

        [JsonProperty("b:SequenceNumeric", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BSequenceNumeric { get; set; }
    }

    public partial class BInvoiceLineBAllowanceCharges
    {
        [JsonProperty("b:AllowanceCharge", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BAllowanceChargeUnion? BAllowanceCharge { get; set; }
    }

    public partial class BItem
    {
        [JsonProperty("b:AdditionalItemIdentifications")]
        public virtual BAdditionalItemIdentifications BAdditionalItemIdentifications { get; set; }

        [JsonProperty("b:BrandName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBrandName { get; set; }

        [JsonProperty("b:BuyersItemIdentification", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BBuyersItemIdentification { get; set; }

        [JsonProperty("b:CommodityClassification")]
        public virtual dynamic BCommodityClassification { get; set; }

        [JsonProperty("b:CommodityClassificationCodes", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BCommodityClassificationCodes BCommodityClassificationCodes { get; set; }

        [JsonProperty("b:Description", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BDescription { get; set; }

        [JsonProperty("b:ItemClassificationCode")]
        public virtual BItemBItemClassificationCode BItemClassificationCode { get; set; }

        [JsonProperty("b:ManufacturersItemIdentification", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BManufacturersItemIdentification { get; set; }

        [JsonProperty("b:ModelName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BModelName { get; set; }

        [JsonProperty("b:Name", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BName { get; set; }

        [JsonProperty("b:OriginCountry", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BOriginCountry { get; set; }

        [JsonProperty("b:ProductTraceID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BProductTraceId { get; set; }

        [JsonProperty("b:SellersItemIdentification", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BSellersItemIdentification { get; set; }

        [JsonProperty("b:SerialID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BSerialId { get; set; }
    }

    public partial class BAdditionalItemIdentifications
    {
        [JsonProperty("b:AdditionalItemIdentification", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<Identification> BAdditionalItemIdentification { get; set; }
    }

    public partial class BCommodityClassificationCodes
    {
        [JsonProperty("@xmlns:c", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsC { get; set; }

        //[JsonConverter(typeof(CStringConverter))]
        //[JsonProperty("c:string", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual List<string> CString { get; set; }
    }

    public partial class BItemBItemClassificationCode
    {
        [JsonProperty("b:ItemClassificationCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BItemClassificationCodeBItemClassificationCode BItemClassificationCode { get; set; }
    }

    public partial class BItemClassificationCodeBItemClassificationCode
    {
        [JsonProperty("b:Value")]
        public virtual dynamic BValue { get; set; }

        [JsonProperty("b:listAgencyID")]
        public virtual dynamic BListAgencyId { get; set; }

        [JsonProperty("b:listID")]
        public virtual dynamic BListId { get; set; }

        [JsonProperty("b:listName", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BListName { get; set; }

        [JsonProperty("b:listVersionID", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BListVersionId { get; set; }
    }

    public partial class BInvoiceLineBNotes
    {
        [JsonProperty("@xmlns:c", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsC { get; set; }

        //[JsonProperty("c:string", NullValueHandling = NullValueHandling.Ignore)]
        //[JsonConverter(typeof(CStringConverter))]
        //public virtual List<string> CString { get; set; }
    }

    public partial class BInvoiceLineBTaxTotal
    {
        [JsonProperty("b:TaxAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BTaxAmount { get; set; }

        [JsonProperty("b:TaxSubtotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BTaxTotalBTaxSubtotal BTaxSubtotal { get; set; }
    }

    public partial class BTaxTotalBTaxSubtotal
    {
        [JsonProperty("b:TaxSubtotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BTaxSubtotalBTaxSubtotal BTaxSubtotal { get; set; }
    }

    public partial class BTaxSubtotalBTaxSubtotal
    {
        [JsonProperty("b:BaseUnitMeasure", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BBaseUnitMeasure { get; set; }

        [JsonProperty("b:BaseUnitMeasureCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BBaseUnitMeasureCode { get; set; }

        [JsonProperty("b:CalculationSequenceNumeric", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DoubleParseStringConverter))]
        public virtual double? BCalculationSequenceNumeric { get; set; }

        [JsonProperty("b:PerUnitAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Amount BPerUnitAmount { get; set; }

        [JsonProperty("b:Percent", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DoubleParseStringConverter))]
        public virtual double? BPercent { get; set; }

        [JsonProperty("b:TaxAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BTaxAmount { get; set; }

        [JsonProperty("b:TaxCategoryExemptionReason", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTaxCategoryExemptionReason { get; set; }

        [JsonProperty("b:TaxCategoryExemptionReasonCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTaxCategoryExemptionReasonCode { get; set; }

        [JsonProperty("b:TaxCategorySchemeCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTaxCategorySchemeCode { get; set; }

        [JsonProperty("b:TaxCategorySchemeName", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BTaxCategorySchemeName { get; set; }

        [JsonProperty("b:TaxableAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BTaxableAmount { get; set; }

        [JsonProperty("b:TransactionCurrencyTaxAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Amount BTransactionCurrencyTaxAmount { get; set; }
    }

    public partial class BLegalMonetaryTotal
    {
        [JsonProperty("b:AllowanceTotalAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BAllowanceTotalAmount { get; set; }

        [JsonProperty("b:ChargeTotalAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Amount BChargeTotalAmount { get; set; }

        [JsonProperty("b:LineExtensionAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BLineExtensionAmount { get; set; }

        [JsonProperty("b:PayableAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BPayableAmount { get; set; }

        [JsonProperty("b:PayableRoundingAmount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Amount BPayableRoundingAmount { get; set; }

        [JsonProperty("b:TaxExclusiveAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BTaxExclusiveAmount { get; set; }

        [JsonProperty("b:TaxInclusiveAmount", NullValueHandling = NullValueHandling.Ignore)]

        public virtual BAmount BTaxInclusiveAmount { get; set; }
    }

    public partial class ABodyBNotes
    {
        [JsonProperty("@xmlns:c", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsC { get; set; }

        //[JsonConverter(typeof(CStringConverter))]
        //[JsonProperty("c:string", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual List<string> CString { get; set; }
    }

    public partial class BOrderReference
    {
        [JsonProperty("b:DocumentReference")]
        public virtual dynamic BDocumentReference { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:IssueDate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BIssueDate { get; set; }

        [JsonProperty("b:OrderTypeCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BOrderTypeCode { get; set; }

        [JsonProperty("b:SalesOrderID", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BSalesOrderId { get; set; }

        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }
    }

    public partial class ABodyBPaymentMeans
    {
        [JsonProperty("b:PaymentMeans", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPaymentMeansBPaymentMeans BPaymentMeans { get; set; }
    }

    public partial class BPaymentMeansBPaymentMeans
    {
        //[JsonProperty("b:InstructionNote", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual AViewContent BInstructionNote { get; set; }

        [JsonProperty("b:PayeeFinancialAccount", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BPayeeFinancialAccount BPayeeFinancialAccount { get; set; }

        //[JsonProperty("b:PayerFinancialAccount", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual AViewContent BPayerFinancialAccount { get; set; }

        //[JsonProperty("b:PaymentChannelCode", NullValueHandling = NullValueHandling.Ignore)]
        //public virtual AViewContent BPaymentChannelCode { get; set; }

        [JsonProperty("b:PaymentDueDate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BPaymentDueDate { get; set; }

        [JsonProperty("b:PaymentMeansCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BPaymentMeansCode { get; set; }
    }

    public partial class BPayeeFinancialAccount
    {
        [JsonProperty("b:CurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BCurrencyCode { get; set; }

        [JsonProperty("b:FinancialInstitutionBranch", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BFinancialInstitutionBranch BFinancialInstitutionBranch { get; set; }

        [JsonProperty("b:ID", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BId { get; set; }

        [JsonProperty("b:PaymentNote", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BPaymentNote { get; set; }
    }

    public partial class BFinancialInstitutionBranch
    {
        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }

        [JsonProperty("b:FinancialInstitution", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BFinancialInstitution { get; set; }

        [JsonProperty("b:Name", NullValueHandling = NullValueHandling.Ignore)]
        public virtual AViewContent BName { get; set; }
    }

    public partial class BPaymentTerms
    {
        [JsonProperty("@i:nil", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(BoolParseStringConverter))]
        public virtual bool? INil { get; set; }

        [JsonProperty("b:Amount", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DoubleParseStringConverter))]
        public virtual double? BAmount { get; set; }

        [JsonProperty("b:Note", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BNote { get; set; }

        [JsonProperty("b:PaymentDueDate", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BPaymentDueDate { get; set; }

        [JsonProperty("b:PenaltyAmount", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DoubleParseStringConverter))]
        public virtual double? BPenaltyAmount { get; set; }

        [JsonProperty("b:PenaltySurchargePercent", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DoubleParseStringConverter))]
        public virtual double? BPenaltySurchargePercent { get; set; }

        [JsonProperty("b:SettlementPeriod", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(NilStringParseCodeConverter))]
        public virtual string BSettlementPeriod { get; set; }
    }

    public partial class ABodyBTaxTotal
    {
        [JsonProperty("b:TaxTotal", NullValueHandling = NullValueHandling.Ignore)]
        public virtual BInvoiceLineBTaxTotal BTaxTotal { get; set; }
    }

    public partial class AHeader
    {
        [JsonProperty("@xmlns:b", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri XmlnsB { get; set; }

        [JsonProperty("b:HashValue", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BHashValue { get; set; }

        [JsonProperty("b:OperationDirectionType", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BOperationDirectionType { get; set; }

        [JsonProperty("b:ReceiveDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? BReceiveDateTime { get; set; }

        [JsonProperty("b:ReceiverAlias", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BReceiverAlias { get; set; }

        [JsonProperty("b:ReferenceNumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? BReferenceNumber { get; set; }

        [JsonProperty("b:SenderAlias", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BSenderAlias { get; set; }

        [JsonProperty("b:SenderIdentityNumber", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string BSenderIdentityNumber { get; set; }

        [JsonProperty("b:ViewUrl", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri BViewUrl { get; set; }
    }

    public partial class Header
    {
        [JsonProperty("@xmlns", NullValueHandling = NullValueHandling.Ignore)]
        public virtual Uri Xmlns { get; set; }

        [JsonProperty("Message")]
        public virtual dynamic Message { get; set; }

        [JsonProperty("ResponseCode", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string ResponseCode { get; set; }

        [JsonProperty("Status", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(LongParseStringConverter))]
        public virtual long? Status { get; set; }
    }


    //public partial struct NilStringParse
    //{
    //    public AViewContent AViewContent;
    //    public string? String;

    //    public static implicit operator NilStringParse(AViewContent AViewContent) => new NilStringParse { AViewContent = AViewContent };
    //    public static implicit operator NilStringParse(string String) => new NilStringParse { String = String };
    //}


    public partial struct BNilLong
    {
        public AViewContent AViewContent;
        public long? Integer;

        public static implicit operator BNilLong(AViewContent AViewContent) => new BNilLong { AViewContent = AViewContent };
        public static implicit operator BNilLong(long Integer) => new BNilLong { Integer = Integer };
    }

    public partial struct BDocumentReferenceUnion
    {
        public BDocumentReferenceElement BDocumentReferenceElement;
        public List<BDocumentReferenceElement> BDocumentReferenceElementArray;

        public static implicit operator BDocumentReferenceUnion(BDocumentReferenceElement BDocumentReferenceElement) => new BDocumentReferenceUnion { BDocumentReferenceElement = BDocumentReferenceElement };
        public static implicit operator BDocumentReferenceUnion(List<BDocumentReferenceElement> BDocumentReferenceElementArray) => new BDocumentReferenceUnion { BDocumentReferenceElementArray = BDocumentReferenceElementArray };
    }

    public partial struct BAllowanceChargeUnion
    {
        public BAllowanceChargeElement BAllowanceChargeElement;
        public List<BAllowanceChargeElement> BAllowanceChargeElementArray;

        public static implicit operator BAllowanceChargeUnion(BAllowanceChargeElement BAllowanceChargeElement) => new BAllowanceChargeUnion { BAllowanceChargeElement = BAllowanceChargeElement };
        public static implicit operator BAllowanceChargeUnion(List<BAllowanceChargeElement> BAllowanceChargeElementArray) => new BAllowanceChargeUnion { BAllowanceChargeElementArray = BAllowanceChargeElementArray };
    }

    public partial struct BNote
    {
        public AViewContent AViewContent;
        public string? String;

        public static implicit operator BNote(AViewContent AViewContent) => new BNote { AViewContent = AViewContent };
        public static implicit operator BNote(string String) => new BNote { String = String };
        public bool IsNull => AViewContent == null && String == null;
    }

    public partial class GelenFaturaResponse
    {
        public static GelenFaturaResponse FromJson(string json) => JsonConvert.DeserializeObject<GelenFaturaResponse>(json, MACHINEBISS_Web.Models.EFatura.EFatGelen.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GelenFaturaResponse self) => JsonConvert.SerializeObject(self, MACHINEBISS_Web.Models.EFatura.EFatGelen.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                DoubleParseStringConverter.Singleton,
                NilLongParseCodeConverter.Singleton,
                NilStringParseCodeConverter.Singleton,
                BDocumentReferenceUnionConverter.Singleton,
                BAllowanceChargeUnionConverter.Singleton,
                BNoteConverter.Singleton,
                CStringConverter.Singleton,
                AViewContentConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class LongParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly LongParseStringConverter Singleton = new LongParseStringConverter();
    }


    internal class DoubleParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(double) || t == typeof(double?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null || reader.TokenType == JsonToken.StartObject) return null;
            var value = serializer.Deserialize<string>(reader);
            double l;
            if (double.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type double");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (double)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly DoubleParseStringConverter Singleton = new DoubleParseStringConverter();
    }



    internal class AViewContentConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(AViewContent);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            return null;
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            return;
        }

        public static readonly AViewContentConverter Singleton = new AViewContentConverter();
    }

    internal class BoolParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(bool) || t == typeof(bool?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            bool b;
            if (Boolean.TryParse(value, out b))
            {
                return b;
            }
            throw new Exception("Cannot unmarshal type bool");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (bool)untypedValue;
            var boolString = value ? "true" : "false";
            serializer.Serialize(writer, boolString);
            return;
        }

        public static readonly BoolParseStringConverter Singleton = new BoolParseStringConverter();
    }

    internal class NilStringParseCodeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        readonly JsonSerializer defaultSerializer = new JsonSerializer();

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = defaultSerializer.Deserialize<string>(reader);
                    return stringValue;
                default:
                    return (string)null;
            }
            throw new Exception("Cannot unmarshal type NilStringParse");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            throw new Exception("Desteklenmiyor!");
        }

        public static readonly NilStringParseCodeConverter Singleton = new NilStringParseCodeConverter();
    }


    internal class NilLongParseCodeConverter : JsonConverter
    {

        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        readonly JsonSerializer defaultSerializer = new JsonSerializer();

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null || reader.TokenType == JsonToken.StartObject) return null;
            if (reader.TokenType == JsonToken.Integer) return defaultSerializer.Deserialize(reader, t);
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly NilLongParseCodeConverter Singleton = new NilLongParseCodeConverter();
    }

    internal class BDocumentReferenceUnionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BDocumentReferenceUnion) || t == typeof(BDocumentReferenceUnion?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<BDocumentReferenceElement>(reader);
                    return new BDocumentReferenceUnion { BDocumentReferenceElement = objectValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<List<BDocumentReferenceElement>>(reader);
                    return new BDocumentReferenceUnion { BDocumentReferenceElementArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type BDocumentReferenceUnion");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (BDocumentReferenceUnion)untypedValue;
            if (value.BDocumentReferenceElementArray != null)
            {
                serializer.Serialize(writer, value.BDocumentReferenceElementArray);
                return;
            }
            if (value.BDocumentReferenceElement != null)
            {
                serializer.Serialize(writer, value.BDocumentReferenceElement);
                return;
            }
            throw new Exception("Cannot marshal type BDocumentReferenceUnion");
        }

        public static readonly BDocumentReferenceUnionConverter Singleton = new BDocumentReferenceUnionConverter();
    }

    internal class BAllowanceChargeUnionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BAllowanceChargeUnion) || t == typeof(BAllowanceChargeUnion?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<BAllowanceChargeElement>(reader);
                    return new BAllowanceChargeUnion { BAllowanceChargeElement = objectValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<List<BAllowanceChargeElement>>(reader);
                    return new BAllowanceChargeUnion { BAllowanceChargeElementArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type BAllowanceChargeUnion");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (BAllowanceChargeUnion)untypedValue;
            if (value.BAllowanceChargeElementArray != null)
            {
                serializer.Serialize(writer, value.BAllowanceChargeElementArray);
                return;
            }
            if (value.BAllowanceChargeElement != null)
            {
                serializer.Serialize(writer, value.BAllowanceChargeElement);
                return;
            }
            throw new Exception("Cannot marshal type BAllowanceChargeUnion");
        }

        public static readonly BAllowanceChargeUnionConverter Singleton = new BAllowanceChargeUnionConverter();
    }

    internal class BNoteConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BNote) || t == typeof(BNote?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Null:
                    return new BNote { };
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new BNote { String = stringValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<AViewContent>(reader);
                    return new BNote { AViewContent = objectValue };
            }
            throw new Exception("Cannot unmarshal type BNote");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (BNote)untypedValue;
            if (value.IsNull)
            {
                serializer.Serialize(writer, null);
                return;
            }
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            if (value.AViewContent != null)
            {
                serializer.Serialize(writer, value.AViewContent);
                return;
            }
            throw new Exception("Cannot marshal type BNote");
        }

        public static readonly BNoteConverter Singleton = new BNoteConverter();
    }

    internal class CStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(List<string>);

        readonly JsonSerializer defaultSerializer = new JsonSerializer();

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    return null;
                case JsonToken.StartArray:
                    var arrayValue = defaultSerializer.Deserialize<List<string>>(reader);
                    return arrayValue;
                case JsonToken.String:
                    var stringValue = defaultSerializer.Deserialize<string>(reader);
                    return new List<string> { stringValue };
            }
            throw new Exception("Cannot unmarshal type CString");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            throw new Exception("Desteklenmiyor");
        }

        public static readonly CStringConverter Singleton = new CStringConverter();
    }
}
